#!/usr/bin/env python3
"""
gen_sym_table.py — emit beacon_syms_enc.h with XOR-obfuscated Beacon API names.

Each build picks a fresh random key so the encoded byte sequence changes every
compile.  The C loader decodes names at runtime before comparing against COFF
symbol table entries, so no plaintext Beacon API strings appear in .rdata.

Index order MUST stay in sync with _sym_ptrs[] in bof_loader.c.
"""
import secrets
import sys

NAMES = [
    "BeaconOutput",
    "BeaconPrintf",
    "BeaconDataParse",
    "BeaconDataExtract",
    "BeaconDataInt",
    "BeaconDataShort",
    "BeaconDataLength",
    "BeaconFormatAlloc",
    "BeaconFormatReset",
    "BeaconFormatFree",
    "BeaconFormatAppend",
    "BeaconFormatPrintf",
    "BeaconFormatToString",
    "BeaconFormatInt",
    "BeaconIsAdmin",
    "BeaconIsAdmIn",   # Cobalt Strike spelling variant — maps to BeaconIsAdmin
    "BeaconUseToken",
    "BeaconRevertToken",
    "BeaconSpawnTemporaryProcess",
    "BeaconInjectProcess",
    "BeaconInjectTemporaryProcess",
    "BeaconCleanupProcess",
    "BeaconAddValue",
    "BeaconGetValue",
    "BeaconRemoveValue",
    "toWideChar",
]


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "beacon_syms_enc.h"
    key = secrets.randbits(8)

    lines = [
        "#pragma once",
        f"/* Auto-generated by gen_sym_table.py — DO NOT EDIT */",
        f"#define SYM_XOR_KEY 0x{key:02x}U",
        "",
    ]

    for i, name in enumerate(NAMES):
        enc = ", ".join(f"0x{(b ^ key) & 0xFF:02x}" for b in name.encode("ascii"))
        lines.append(f"static const unsigned char _sn{i}[] = {{ {enc} }};")

    lines += [
        "",
        "static const struct {",
        "    const unsigned char *enc;",
        "    unsigned char        len;",
        "} _sym_encs[] = {",
    ]
    for i, name in enumerate(NAMES):
        lines.append(f"    {{ _sn{i}, {len(name)} }},")
    lines += ["    { 0, 0 }", "};", ""]

    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"[+] {out}  (key=0x{key:02x}, {len(NAMES)} symbols)")


if __name__ == "__main__":
    main()
